feat: Allow setting openOnHover for DropdownMenu
nulogy/design-system pull request #1076
Opened 2023-02-09 20:29 UTC by melissap-nulogy

## Description

Allow openOnHover to be sent into DropdownMenu to enable a use case where we have nested DropdownMenus. Added a storybook story.

## Changes include

- [ ] breaking change: a change that is not backwards-compatible and/or changes current functionality
- [ ] fix: a non-breaking change that solves an issue
- [x ] feature: a non-breaking change that adds functionality
- [ ] chore: contains no changes affecting the library, such as documentation or test updates

## Feature checklist

- [ ] Appropriate tests have been added
- [ ] Documentation has been updated
- [ ] Accessibility has been considered

2023-02-09 21:04 UTC, haideralsh commented on src/DropdownMenu/DropdownMenu.story.tsx
> +            <Text>&gt;</Text>
Can we change this to an icon instead?
```suggestion
           <Icon icon="rightArrow" title="right arrow" />;
```

2023-02-09 21:08 UTC, haideralsh commented on src/DropdownMenu/DropdownMenu.story.tsx
> +export const WithSubmenu = () => (
Since this change involves interactivity, is it possible to test the storybook you added in the `cypress/integration/components/DropdownMenu.spec.js` to insure coverage of this feature?

2023-02-09 21:10 UTC, haideralsh requested changes
@melissap-nulogy thanks for creating this PR. I left a couple of comments.

2023-02-09 21:11 UTC, melissap-nulogy commented on src/DropdownMenu/DropdownMenu.story.tsx
> +export const WithSubmenu = () => (
I looked for a spec and didnt find this one for some reason, will add a test

2023-02-10 15:49 UTC, haideralsh approved these changes

2023-02-10 15:51 UTC, merged