Nds 499 code inlineerror
nulogy/design-system pull request #125
Opened 2019-01-23 20:52 UTC by nikola-nulogy

What I did

- Added Inline validation component and story

2019-01-24 18:01 UTC, clemensp requested changes

2019-01-24 20:10 UTC, nikola-nulogy commented on docs/src/markdown/get-started/get-started.md
> +s](logos.png)
No, it wasn't and it is fixed now.

2019-01-24 20:10 UTC, nikola-nulogy commented on docs/src/markdown/get-started/get-started.md
> +
I guess so and it is fixed now.

2019-01-24 22:45 UTC, clemensp commented on components/src/Validation/InlineValidation.js
> +      <Icon size={ theme.space[4] } name={ props.icon } mr={ 1 } />
Do we want to try the `icon={ {name: "error"} }` approach here?

2019-01-25 15:53 UTC, clemensp approved these changes
Changes look good.

Can you address the one comment I left?
After that, looks good to merge.

2019-01-25 15:53 UTC, clemensp commented on components/src/Icon/Icon.js
> +  color: "currentColor",
I took a look at the `InlineIcon` proptypes, and it looks like they're not needed anymore.
Could you remove those?

2019-01-25 15:57 UTC, merged