Nds 494 code toggle
nulogy/design-system pull request #142
Opened 2019-01-30 21:56 UTC by coostenbrug

Adds Toggle and Toggle Stories
This toggle supports animation, accessibility, and correctly works with focus

Use the story marked with <TEMP> to see the functionality of the toggle and its various props. (We can remove this story later if we don't want demonstrations of functionality like this in storybook)

the starting basis of the component came from here: 
https://github.com/aaronshaf/react-toggle/blob/master/src/component/index.js

2019-01-30 22:42 UTC, clemensp requested changes
@coostenbrug : There's quite a bit going on in this one, so I'd like to pair with you for the review.

I checked it out in storybook, and the behaviour is nice. Looks great too!
Probably need @nikola-nulogy to review the box shadow, etc. =) 

On first pass, I see something that will have to be changed.
The standard API for react form elements is:
- value
- onChange
- defaultValue

You can also choose whether the form component is controlled or not:
https://reactjs.org/docs/forms.html#controlled-components

Let's work on those together.

I also wonder if we should simplify the Toggle to be just the pill, which can be an atom.
We could then introduce a ToggleField as a molecule, and compose it with `Field`, `Toggle`, and something that represents the value, possible just `Text`?

Looking forward to the discussion! :)

2019-01-30 22:42 UTC, clemensp commented on components/src/Toggle/Toggle.js
> +    return false;
What does false do?

2019-01-31 21:00 UTC, nikola-nulogy commented
The disabled state should not have pointer cursor.

2019-02-01 20:35 UTC, coostenbrug commented
Closing and moving to the alt branch

2019-02-01 20:35 UTC, closed without merging