Nds 282 base font size correction
nulogy/design-system pull request #43
Opened 2018-09-14 18:03 UTC by nikola-nulogy

What I Did

Changed base font size on Button and Table components

2018-09-14 19:00 UTC, theinterned requested changes
There is a question about line heights we need to address ...

2018-09-18 14:24 UTC, matthewlyle approved these changes

2018-09-18 16:27 UTC, theinterned requested changes

2018-09-18 16:27 UTC, theinterned commented on tokens/src/tokens.js
> +export const fontMetrics = (size = 'medium', target = 'medium') => ({ theme = { font } }) => css`
I'm not sure if `@nulogy/tokens` should be exporting helper functions ... We should aim to keep it as simple as possible and as close to pure json data (even though its actually not technically conferment json atm).

I'm also pretty sure that `@nulogy/tokens` doesn't actually have `styled-components` in its package json. Nor should it.

This should go someplace else: Either a utils folder of the `@nulogy/components` package, or better yet, a new shared package `@nulogy/theme` perhaps?

There is a mediaQuery helper function introduced in PR #42 that would go nicely in that package as well.

2018-09-19 22:44 UTC, theinterned approved these changes

2018-09-19 22:44 UTC, merged